name: Tests (pytest)

on:
  pull_request:
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: dopplerhq/cli-action@v1
      - name: Login in Doppler
        run: |
          doppler secrets download --no-file --format=docker >> $GITHUB_ENV;
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      - uses: actions/checkout@v3
      - name: Set up Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - name: Initialize MySQL Database
        run: |
          mysql -h 127.0.0.1 -u root -p1fVUQ1Jl5jFJt7a gptmax < scripts/dump_prod.sql
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Run migrations
        run: |
          cd src/
          alembic upgrade head
      - name: Test with pytest
        run: |
          pytest
    services:
      # Label used to access the service container
      mysqldb:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1fVUQ1Jl5jFJt7a
          MYSQL_DATABASE: gptmax
          MYSQL_USER: gpmtax
          MYSQL_PASSWORD: NqYffcSmTgntOoY
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
