# name: Tests (pytest)

# on:
#   pull_request:
#   push:
#     branches: [main]

# env:
#   PYTHON_VERSION: "3.10"

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r src/requirements.txt
#       - name: Test with pytest
#         run: |
#           pytest
